void main(){
    int a,b,c;
    c=5;
    a=c<5;
    println(a);
    a=c>=5;
    c=c+(c>=2);
    println(a);
    a=(1<5)&&(2<3);
    b=(1<5)&&(2==3);
    println(b);
   b=(2+(3*5)*9+8)/7;
    println(a);
    println(b);
    b=(1<5)||(2<3);
    println(b);
    b=(1>5)||(2<3);
    println(b);
    b=(1>5)||(2>3);
    println(b);
    b=(1!=5) && (2!=(3-1));
    println(b);
        b=(1!=5) && (2==(3-1));
    println(b);
        b=(1!=5) && (2<=(3-1));
    println(b);
        b=(1!=5) && (2>=(3-1));
    println(b);
        b=(1!=5) && (2>(3-1));
    println(b);
    c=19;
    c=((a==1)&&(b==1))+c;
    println(c);
     c=((a==1)||(b==1))+c;
    println(c);
    c=!c;
    println(c);
    c=!c;
    println(c);
    c=!(2>3);
    println(c);
    c=!((2>3)||(1>2));
    println(c);

}