#define SEMICOLON_R "SEMICOLON : ;"
#define LCURL_R "LCURL : {"
#define RCURL_R "RCURL : }"
#define LPAREN_R "LPAREN : ("
#define RPAREN_R "RPAREN : )"
#define LTHIRD_R "LSQUARE : ["
#define RTHIRD_R "RSQUARE : ]"   
#define COMMA_R "COMMA : , "
#define FOR_R "FOR : for"
#define IF_R "IF : if"
#define ELSE_R "ELSE : else"
#define WHILE_R "WHILE : while"
#define PRINTLN_R "PRINTLN : println"
#define RET_R "RETURN : return"
#define INC_R "INCOP : ++"
#define DEC_R "DECOP : --"
#define NOT_R  "NOT : !"
#define ASSIGN_R "ASSIGNOP : ="